export const cars = [
{
    "make": "Abadal",
    "name": "Abadal 25 HP 1914",
    "year": "Year: 1914",
    "origin": "Spain",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: 4-speed manual",
    "engine": "Engine: 3104 cc four-speed engine",
    "price": "Price: $910.34",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/115",
    "weight": "Weight: 1495 kg",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: 1",
    "image": "https://360carmuseum.com/data/museums/3/expo/365/image/0_xl.jpg"
},

{
    "make": "Abadal",
    "name": "Abadal-Buick 1923",
    "year": "Year: 1923",
    "origin": "Spain",
    "hp": "hp: Unknown",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 4521 cc six-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: 1495 kg",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Abadal-Buick_1923.jpg/1200px-Abadal-Buick_1923.jpg"
},

{
    "make": "Abarth",
    "name": "1500 Biposto Coupe Bertone",
    "year": "Year: 1952",
    "origin": "Italy",
    "hp": "hp: 74",
    "drive": "Drive: RWD",
    "transmission": "Transmission: 4-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG:  20.2",
    "MPHandKPH": "Top Speed(MPH/KPH): 98/158",
    "weight": "Weight: 1918 lbs",
    "zeroto": "0-60(mph): 12.5s",
    "0to60inkph": "na",
    "torque": "Torque: 74 lb-ft",
    "cylinders": "Cylinders: 4",
    "image": "https://www.automobile-catalog.com/img/pictonorzw/abarth/ab-bertone-coupe-1952.jpg"
},

{
    "make": "Abarth",
    "name": "207A Spyder",
    "year": "Year: 1954",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://myntransportblog.files.wordpress.com/2015/11/1955-abarth-207a-spyder-corsa-boano1.jpg?w=840"
},

{
    "make": "Abarth",
    "name": "207A Spyder Boano",
    "year": "Year: 1954",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://i2.wp.com/thechicane.com/wp-content/uploads/2008/11/abarth-207a-boano-spider_2.jpg?ssl=1"
},

{
    "make": "Abarth",
    "name": "2000 Ghia Coupe Concept",
    "year": "Year: 1954",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://i.pinimg.com/originals/56/0f/0d/560f0da9142a93a9a016f9272cc0f379.jpg"
},

{
    "make": "Abarth",
    "name": "208A Spyder Boano",
    "year": "Year: 1955",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://1.bp.blogspot.com/-tCsOURouYtI/VkgEHw4OmtI/AAAAAAAABBM/JzLm4H2NQSc/s1600/-barn-find-1955-abarth.jpg"
},

{
    "make": "Abarth",
    "name": "209A Coupe Boano",
    "year": "Year: 1955",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://c2.staticflickr.com/4/3071/2321139886_a8ccda425a_z.jpg?zz=1"
},

{
    "make": "Abarth",
    "name": "Fiat 600 Berlina Conversions",
    "year": "Year: 1955",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://farm3.static.flickr.com/2493/4191069296_b9a9fbae87.jpg"
},

{
    "make" : "Abarth",
    "name" : "215A Coupe Bertone",
    "year": "Year: 1956",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://i.pinimg.com/originals/03/5f/7b/035f7b3eb0cdca1d7e6e15d4ffffa5aa.jpg"
},

{
    "make" : "Abarth",
    "name" : "216A Spyder Bertone",
    "year": "Year: 1956",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.allcarcentral.com/Abarth/Fiat_Abarth_215A_Bertone_750cc_1956_pb-1992.jpg"
},

{
    "make" : "Abarth",
    "name" : "750 Spider Boano",
    "year": "Year: 1956",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.bernimotori.com/images/cars/210A_1956/210A_1956_1.jpg"
},

{
    "make" : "Abarth",
    "name" : "Fiat 500 Typ 110-120 Conversions",
    "year": "Year: 1957",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://www.automobile-catalog.com/img/pictonorzw/abarth/070321_F_500_08.jpg"
},

{
    "make" : "Abarth",
    "name" : "Fiat 500 Abarth Zagato",
    "year": "Year: 1957",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.carstyling.ru/resources/studios/1957_Zagato_Fiat_Abarth_500_GT_Coupe_08.jpg"
},

{
    "make" : "Abarth",
    "name" : "Fiat 600 Abarth Zagato",
    "year": "Year: 1957",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.carstyling.ru/Static/SIMG/420_0_I_MC_jpg_W/resources/concept/1957_Zagato_Fiat_Abarth_750_GT_Coupe_01.jpg?3F74AEFC272EE6597F227E1ED438FB7D"
},

{
    "make" : "Abarth",
    "name" : "Abarth Alfa Romeo Derivazione",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.carstyling.ru/Static/SIMG/420_0_I_MC_jpg_W/resources/studios/1958-Bertone-Abarth-Alfa-Romeo-1000-Coupe-01.jpg?81ADD4F7FF836DD2D67CAF4CE4AD6612"
},

{
    "make" : "Abarth",
    "name" : "500 Record Pininfarina",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://i2.wp.com/66.media.tumblr.com/c2a0a2ad549ddd653a1e995fa3d6aee8/tumblr_pgon3f9WZp1qb815co1_1280.jpg?w=605&ssl=1"
},

{
    "make" : "Abarth",
    "name" : "Allemano Spider 750",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://www.carandclassic.co.uk/uploads/cars/abarth/10197307.jpg"
},

{
    "make" : "Abarth",
    "name" : "Rekord Monza Zagato Coupe",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://i.pinimg.com/originals/90/de/ef/90deefab1494f592356c9db1b1288d25.jpg"
},

{
    "make": "Abarth",
    "name": "Coupe Allemano 2200-2400",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.bernimotori.com/images/cars/allemano_coupe/allemano_coupe_3.jpg"
},

{
    "make": "Abarth",
    "name": "Sestriere",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://c1.staticflickr.com/5/4053/4511004234_4509e30982_b.jpg"
},

{
    "make": "Abarth",
    "name": "Fiat 600 Abarth Allemano",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://cdn.bringatrailer.com/wp-content/uploads/2012/08/1959_Abarth_750_Allemano_Spider_front_quarter_resize.jpg"
},

{
    "make": "Abarth",
    "name": "Sestriere Coupe",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://www.carfolio.com/images/dbimages/zgas/models/id/4715/abarth%20750%20coup%C3%A9%20zagato%20front%20%C2%BE.jpg"
},

{
    "make": "Abarth",
    "name": "Allemano Coupe-Spider 1600",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.bernimotori.com/images/cars/allemano_coupe/allemano_coupe_11.jpg"
},

{
    "make": "Abarth",
    "name": "Coupe Scorpione Allemano",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "https://www.wallpaperup.com/uploads/wallpapers/2013/06/21/106162/4e180d6598d376b8e626e4e70bb7adf1-700.jpg"
},

{
    "make": "Abarth",
    "name": "Spider 1600 Allemano",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": "http://www.carstyling.ru/Static/SIMG/420_0_I_MC_jpg_W/resources/studios/1959-Allemano-Fiat-Abarth-1600-Spyder-04.jpg?0277994CD2FA880EEC31575A81B113A5"
},

{
    "make": "Abarth",
    "name": "Allemano Coupe-Spider 850",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Spider Riviera Allemano",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Monomille",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "1600 Allemano",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Ellena 2200",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Monomille Coupe",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Simca 1300",
    "year": "Year: 1962",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Simca 1000",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Simca 1150",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Simca 1600",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Simca 2000",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Berlina Corsa",
    "year": "Year: 1964",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Fiat 850 Berlina Conversions",
    "year": "Year: 1964",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "1000 Coupe Speciale Pininfarina",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "1000 OTR Bertone Coupe",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "1000 Pininfarina Spider",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Fiat 850 Coupe Conversions",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Fiat 850 Spider Conversions",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "OT Coupe",
    "year": "Year: 1966",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "OT Sport Spider",
    "year": "Year: 1966",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "1000 Sp",
    "year": "Year: 1967",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "2000 Tubolare",
    "year": "Year: 1967",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "2000 Pininfarina Coupe Concept",
    "year": "Year: 1969",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "3000 Group 6 Racing Car",
    "year": "Year: 1969",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Scorpione",
    "year": "Year: 1969",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Grande Punto",
    "year": "Year: 2007",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "500 Hatchback",
    "year": "Year: 2008",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "500C Convertible",
    "year": "Year: 2010",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695 Hatchback",
    "year": "Year: 2010",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Punto Evo",
    "year": "Year: 2010",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "595 Hatchback phase-I",
    "year": "Year: 2012",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695 Convertible Tributo Maserati",
    "year": "Year: 2012",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "Punto 2012",
    "year": "Year: 2012",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "595C Convertible phase-I",
    "year": "Year: 2013",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695 Biposto",
    "year": "Year: 2015",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "124 Spider",
    "year": "Year: 2016",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "595 Hatchback phase-II",
    "year": "Year: 2016",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "595C Convertible phase-II",
    "year": "Year: 2016",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695 Rivale",
    "year": "Year: 2017",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695 XSR",
    "year": "Year: 2017",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695C Rivale",
    "year": "Year: 2017",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
},

{
    "make": "Abarth",
    "name": "695C XSR",
    "year": "Year: 2017",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na",
    "image": ""
}

]