export const cars = [
{
    "make": "Abadal",
    "name": "Abadal 25 HP 1914",
    "year": "Year: 1914",
    "origin": "Spain",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: 4-speed manual",
    "engine": "Engine: 3104 cc four-speed engine",
    "price": "Price: $910.34",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/115",
    "weight": "Weight: 1495 kg",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: 1"
},

{
    "make": "Abadal",
    "name": "Abadal-Buick 1923",
    "year": "Year: 1923",
    "origin": "Spain",
    "hp": "hp: Unknown",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 4521 cc six-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: 1495 kg",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "1500 Biposto Coupe Bertone",
    "year": "Year: 1952",
    "origin": "Italy",
    "hp": "hp: 74",
    "drive": "Drive: RWD",
    "transmission": "Transmission: 4-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG:  20.2",
    "MPHandKPH": "Top Speed(MPH/KPH): 98/158",
    "weight": "Weight: 1918 lbs",
    "zeroto": "0-60(mph): 12.5s",
    "0to60inkph": "na",
    "torque": "Torque: 74 lb-ft",
    "cylinders": "Cylinders: 4"
},

{
    "make": "Abarth",
    "name": "207A Spyder",
    "year": "Year: 1954",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "207A Spyder Boano",
    "year": "Year: 1954",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "2000 Ghia Coupe Concept",
    "year": "Year: 1954",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "208A Spyder Boano",
    "year": "Year: 1955",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "209A Coupe Boano",
    "year": "Year: 1955",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Fiat 600 Berlina Conversions",
    "year": "Year: 1955",
    "origin": "Italy",
    "hp": "hp: 140",
    "drive": "Drive: FWD",
    "transmission": "Transmission: 5-speed manual",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "215A Coupe Bertone",
    "year": "Year: 1956",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "216A Spyder Bertone",
    "year": "Year: 1956",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "750 Spider Boano",
    "year": "Year: 1956",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Fiat 500 Typ 110-120 Conversions",
    "year": "Year: 1957",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Fiat 500 Abarth Zagato",
    "year": "Year: 1957",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Fiat 600 Abarth Zagato",
    "year": "Year: 1957",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Abarth Alfa Romeo Derivazione",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "500 Record Pininfarina",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Alfa Romeo Conversions",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Allemano Spider 750",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Rekord Monza Zagato Coupe",
    "year": "Year: 1958",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make" : "Abarth",
    "name" : "Cabriolet Allemano 2200-2400",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp" : "hp: n/a",
    "drive" : "Drive: n/a",
    "transmission" : "Transmission: n/a",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Coupe Allemano 2200-2400",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Sestriere",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Fiat 600 Abarth Allemano",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Sestriere Coupe",
    "year": "Year: 1959",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Allemano Coupe-Spider 1600",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Coupe Scorpione Allemano",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Spider 1600 Allemano",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Allemano Coupe-Spider 850",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Spider Riviera Allemano",
    "year": "Year: 1960",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Monomille",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "1600 Allemano",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Ellena 2200",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Monomille Coupe",
    "year": "Year: 1961",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Simca 1300",
    "year": "Year: 1962",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Simca 1000",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Simca 1150",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Simca 1600",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Simca 2000",
    "year": "Year: 1963",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Berlina Corsa",
    "year": "Year: 1964",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Fiat 850 Berlina Conversions",
    "year": "Year: 1964",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "1000 Coupe Speciale Pininfarina",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "1000 OTR Bertone Coupe",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "1000 Pininfarina Spider",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Fiat 850 Coupe Conversions",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Fiat 850 Spider Conversions",
    "year": "Year: 1965",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "OT Coupe",
    "year": "Year: 1966",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "OT Sport Spider",
    "year": "Year: 1966",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "1000 Sp",
    "year": "Year: 1967",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "2000 Tubolare",
    "year": "Year: 1967",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "2000 Pininfarina Coupe Concept",
    "year": "Year: 1969",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "3000 Group 6 Racing Car",
    "year": "Year: 1969",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Scorpione",
    "year": "Year: 1969",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Grande Punto",
    "year": "Year: 2007",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "500 Hatchback",
    "year": "Year: 2008",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "500C Convertible",
    "year": "Year: 2010",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "695 Hatchback",
    "year": "Year: 2010",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Punto Evo",
    "year": "Year: 2010",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "595 Hatchback phase-I",
    "year": "Year: 2012",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "695 Convertible Tributo Maserati",
    "year": "Year: 2012",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "Punto 2012",
    "year": "Year: 2012",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "595C Convertible phase-I",
    "year": "Year: 2013",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "695 Biposto",
    "year": "Year: 2015",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "124 Spider",
    "year": "Year: 2016",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "595 Hatchback phase-II",
    "year": "Year: 2016",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "595C Convertible phase-II",
    "year": "Year: 2016",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "695 Rivale",
    "year": "Year: 2017",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "500 Hatchback",
    "year": "Year: 2008",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "500 Hatchback",
    "year": "Year: 2008",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
},

{
    "make": "Abarth",
    "name": "500 Hatchback",
    "year": "Year: 2008",
    "origin": "Italy",
    "hp": "hp: 25",
    "drive": "Drive: Unknown",
    "transmission": "Transmission: Unknown",
    "engine": "Engine: 3104 cc four-cylinder engine",
    "price": "Price: n/a",
    "MPG": "MPG: n/a",
    "MPHandKPH": "Top Speed(MPH/KPH): na/na",
    "weight": "Weight: n/a",
    "zeroto": "0-60(mph): na",
    "0to60inkph": "0-60 in KPH: na",
    "torque": "Torque: na",
    "cylinders": "Cylinders: na"
}

]